// Mocks generated by Mockito 5.4.6 from annotations
// in app_money_flow/test/features/home/accounts/unit/accounts_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_money_flow/src/core/models/bank_account_model.dart' as _i5;
import 'package:app_money_flow/src/core/services/bank_accounts_service.dart'
    as _i3;
import 'package:app_money_flow/src/core/services/http/http_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpClient_0 extends _i1.SmartFake implements _i2.HttpClient {
  _FakeHttpClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BankAccountsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBankAccountsService extends _i1.Mock
    implements _i3.BankAccountsService {
  MockBankAccountsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HttpClient get http => (super.noSuchMethod(
        Invocation.getter(#http),
        returnValue: _FakeHttpClient_0(
          this,
          Invocation.getter(#http),
        ),
      ) as _i2.HttpClient);

  @override
  _i4.Future<List<_i5.BankAccountModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i5.BankAccountModel>>.value(
            <_i5.BankAccountModel>[]),
      ) as _i4.Future<List<_i5.BankAccountModel>>);

  @override
  _i4.Future<dynamic> create(_i5.BankAccountModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [model],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> update(_i5.BankAccountModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [model],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<void> remove(String? bankAccountId) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [bankAccountId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
